# This is a basic workflow to help you get started with Actions

name: "build-for-release"

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python_version: ['3.10.x']
        
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python_version }}
        
      - name: installing dependancy & build
        run: |
          pip install pyinstaller
          pyinstaller -D -N prototype
        
      - name: preparing for release
        run: |
          mv dist/__app__.exe release/proto.exe
        
      - name: release installer
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Stable Build"
          files: |
            release/*
